### ISSUE TITLE
box-sizing option breaks requirement to insert the @import rule at the beginning of the CSS document

### ISSUE THREAD

**Issue by plesiecki** [jonathantneal/postcss-time-machine#9]
Hello @jonathantneal 

Let's consider following scenario:

for following input

``` scss
@import 'https://fonts.googleapis.com/css?family=Roboto';

.foo {}
```

postcss-time-machine with box-sizing enabled outputs 

``` scss
* {
 box-sizing: border-box;
}
@import 'https://fonts.googleapis.com/css?family=Roboto';

.foo {}
```

so it breaks requirement to insert the @import rule at the beginning of the CSS document.

reference: https://developer.mozilla.org/en/docs/Web/CSS/@import
